Going for exception tasks in python
